/** Official 物件概要 — Japanese source copy. */
export const summaryOverviewJp = {
  name: "エルファーロプラス白金高輪 新築工事",
  lotNumber: "東京都港区三田５丁目１番５２",
  address: "東京都港区三田５丁目５番１０号",
  siteArea: "148.83 ㎡ (建築確認申請書 記載面積)",
  zoning: "商業地域",
  fireZone: "防火地域",
  coverage: "80％（指定）100.00％（許容）（準防火地域内の耐火建築物）",
  far: "500％（指定）320.00％（許容）（道路幅員 4m×0.8）",
  heightDistrict: "40m 高度地区",
  other: "第二種文教地区",
  mainUse: "共同住宅（14 戸）",
  totalFloorArea: "541.28 ㎡",
  constructionType: "新築工事",
  buildingArea: "110.56 ㎡",
  buildingCoverage: "74.29%",
  constructionPeriod: "令和７年１２月１日〜令和８年１１月上旬竣工（予定）",
  structure: "鉄筋コンクリート造・地上５階建て",
  farFloorArea: "466.86 ㎡",
  floorAreaRatio: "313.69%",
  fireResistance: "耐火建築物",
  elevator: "1 基",
  parking: "-",
  permitNumber: "未定",
  bicycleParking: "1 台 (屋根なし)",
  motorcycleParking: "-",
  privateArea: "20.02 ㎡ (1K) 〜 47.58 ㎡ (2LDK)",
  developer:
    "東京都目黒区目黒 2-10-11 目黒山手プレイス 4 階\n株式会社明豊エンタープライズ",
};

/** Official 物件概要 — Traditional Chinese. */
export const summaryOverviewZh = {
  name: "EL FARO＋白金高輪 新建工程",
  lotNumber: "東京都港區三田5丁目1番52",
  address: "東京都港區三田5丁目5番10號",
  siteArea: "148.83 ㎡（建築確認申請書記載面積）",
  zoning: "商業區",
  fireZone: "防火區",
  coverage: "80%（指定）100.00%（容許）（準防火區域內之耐火建築物）",
  far: "500%（指定）320.00%（容許）（道路寬度 4m×0.8）",
  heightDistrict: "40m 高度地區",
  other: "第二種文教地區",
  mainUse: "集合住宅（14戶）",
  totalFloorArea: "541.28 ㎡",
  constructionType: "新建工程",
  buildingArea: "110.56 ㎡",
  buildingCoverage: "74.29%",
  constructionPeriod: "令和7年12月1日〜令和8年11月上旬竣工（預定）",
  structure: "鋼筋混凝土造・地上5層",
  farFloorArea: "466.86 ㎡",
  floorAreaRatio: "313.69%",
  fireResistance: "耐火建築物",
  elevator: "1部",
  parking: "-",
  permitNumber: "未定",
  bicycleParking: "1台（無屋頂）",
  motorcycleParking: "-",
  privateArea: "20.02 ㎡（1K）〜 47.58 ㎡（2LDK）",
  developer:
    "東京都目黑區目黑 2-10-11 目黑山手Place 4樓\n株式會社明豐企業",
};
