export const summaryPageDataZh = {
  overview: {
    name: "エルファーロプラス白金高輪 新建工程",
    lotNumber: "東京都港區三田5丁目1番52",
    address: "東京都港區三田5丁目5番10號",
    siteArea: "148.83 ㎡（建築確認申請書記載面積）",
    zoning: "商業區域",
    fireZone: "防火區域",
    coverage: "80%（指定）100.00%（容許）（準防火區域內之耐火建築物）",
    far: "500%（指定）320.00%（容許）（道路寬度 4m × 0.8）",
    heightDistrict: "40m 高度地區",
    other: "第二種文教地區",
    mainUse: "集合住宅（14戶）",
    totalFloorArea: "541.28 ㎡",
    constructionType: "新建工程",
    buildingArea: "110.56 ㎡",
    buildingCoverage: "74.29%",
    constructionPeriod: "令和7年12月1日～令和8年11月上旬竣工（預定）",
    structure: "鋼筋混凝土造・地上5層",
    farFloorArea: "466.86 ㎡",
    floorAreaRatio: "313.69%",
    fireResistance: "耐火建築物",
    elevator: "1部",
    parking: "—",
    permitNumber: "未定",
    bicycleParking: "1台（無屋頂）",
    motorcycleParking: "—",
    privateArea: "20.02 ㎡（1K）～ 47.58 ㎡（2LDK）",
    developer:
      "東京都目黑區目黑2-10-11 目黑山手Place 4樓／株式会社明豐企業",
  },
  floorPlans: [
    {
      floor: "1F 平面圖",
      units: [
        { type: "A", layout: "2LDK", rooms: "101號", area: "47.58 m²", tsubo: "14.39 坪" },
        { type: "B", layout: "1LDK", rooms: "102號", area: "37.13 m²", tsubo: "11.23 坪" },
      ],
    },
    {
      floor: "2F–4F 平面圖",
      units: [
        { type: "C", layout: "1LDK", rooms: "201 / 301 / 401 號", area: "37.67 m²", tsubo: "11.40 坪" },
        { type: "D", layout: "1K", rooms: "202 / 302 / 402 號", area: "20.66 m²", tsubo: "6.25 坪" },
        { type: "E", layout: "1LDK", rooms: "203 / 303 / 403 號", area: "37.92 m²", tsubo: "11.47 坪" },
      ],
    },
    {
      floor: "5F 平面圖",
      units: [
        { type: "F", layout: "1LDK", rooms: "501號", area: "31.26 m²", tsubo: "9.46 坪" },
        { type: "G", layout: "1K", rooms: "502號", area: "20.02 m²", tsubo: "6.06 坪" },
        { type: "H", layout: "1LDK", rooms: "503號", area: "33.46 m²", tsubo: "10.12 坪" },
      ],
    },
  ],
  interiorRows: [
    { room: "門廊", floor: "磁器質瓷磚", floorSub: "—", baseboard: "木質踢腳板", wall: "塑膠壁紙", wallSub: "PB t=12.5", ceiling: "塑膠壁紙", ceilingSub: "PB t=9.5", height: "—" },
    { room: "樓梯間・共用走廊", floor: "防滑塑膠地板", floorSub: "—", baseboard: "木質踢腳板", wall: "塑膠壁紙", wallSub: "PB t=12.5", ceiling: "塑膠壁紙", ceilingSub: "PB t=9.5", height: "—" },
    { room: "玄關", floor: "磁器質瓷磚", floorSub: "自流平材料", baseboard: "木質踢腳板", wall: "塑膠壁紙", wallSub: "PB t=12.5", ceiling: "塑膠壁紙", ceilingSub: "PB t=9.5", height: "2150" },
    { room: "LDK", floor: "木地板", floorSub: "自流平材料", baseboard: "木質踢腳板", wall: "塑膠壁紙", wallSub: "PB t=12.5", ceiling: "塑膠壁紙", ceilingSub: "PB t=9.5", height: "2100" },
    { room: "臥室", floor: "木地板", floorSub: "自流平材料", baseboard: "木質踢腳板", wall: "塑膠壁紙", wallSub: "PB t=12.5", ceiling: "塑膠壁紙", ceilingSub: "PB t=9.5", height: "2275" },
    { room: "收納間", floor: "木地板", floorSub: "自流平材料", baseboard: "木質踢腳板", wall: "塑膠壁紙", wallSub: "PB t=12.5", ceiling: "塑膠壁紙", ceilingSub: "PB t=9.5", height: "2270" },
    { room: "廁所", floor: "磁器質瓷磚", floorSub: "自流平材料", baseboard: "—", wall: "塑膠壁紙", wallSub: "耐水PB", ceiling: "塑膠壁紙", ceilingSub: "耐水PB", height: "2000" },
    { room: "盥洗室", floor: "磁器質瓷磚", floorSub: "自流平材料", baseboard: "—", wall: "塑膠壁紙", wallSub: "耐水PB", ceiling: "塑膠壁紙", ceilingSub: "耐水PB", height: "2000" },
    { room: "洗衣機放置處", floor: "磁器質瓷磚", floorSub: "自流平材料", baseboard: "—", wall: "塑膠壁紙", wallSub: "耐水PB", ceiling: "塑膠壁紙", ceilingSub: "耐水PB", height: "2000" },
    { room: "浴室", floor: "整體浴室", floorSub: "—", baseboard: "—", wall: "整體浴室", wallSub: "—", ceiling: "整體浴室", ceilingSub: "—", height: "—" },
  ],
  equipmentRows: [
    { part: "門廊", spec: "集合玄關機 ●信箱一體型宅配箱（防雨規格）[NASTA] ●管理員聯絡顯示板（樹脂製）300×500 ●滅火器 ●緊急照明 ●引導燈" },
    { part: "樓梯間・共用走廊", spec: "樓梯扶手：樹脂扶手製品 ●踏面・踢面：防滑塑膠地板 ●階梯邊緣：塑膠地板一體型 ●重點瓷磚：各住戶前 W200×H2000 馬賽克邊框・陶彩 BM-OLM-4795/CAR [日泰工業]同等 ●樓層顯示板（不鏽鋼製） ●公告板（A2尺寸） ●滅火器 ●緊急照明 ●引導燈" },
    { part: "玄關", spec: "鞋櫃 ●地板收邊（不鏽鋼-FB） ●崁燈" },
    { part: "LDK", spec: "系統廚房 ●抽油煙機（管線包覆RW） ●空調室內機（設備工程・基層・套管） ●窗簾軌（W） ●進氣口150φ（差壓式・附FD） ●住宅用火災警報器（熱感）" },
    { part: "臥室", spec: "空調室內機（設備工程・基層・套管） ●窗簾軌（W） ●室內曬衣桿 ●進氣口100φ ●住宅用火災警報器（煙感）" },
    { part: "收納間", spec: "掛衣桿（不鏽鋼32φ同等） ●置物架D400" },
    { part: "廁所", spec: "西式馬桶（附溫水洗淨便座／水箱上部洗手） ●衛生紙架 ●毛巾環 ●固定層板 ●崁燈 ●換氣設備（24小時換氣）" },
    { part: "盥洗室", spec: "洗面化妝台L600 ●毛巾環 ●崁燈 ●換氣設備（24小時換氣） ●分電盤" },
    { part: "洗衣機放置處", spec: "洗衣機底座640□（若其他管線通過底座下方，以SL+120薄型為基本。若無其他管線通過且可隱藏管線，亦可採用高架型。）" },
    { part: "浴室", spec: "整體浴室1014/1116 ●浴室換氣暖房乾燥機（24小時換氣） ●掛衣桿（整體浴室附屬品）※符合 JIS A4416。" },
  ],
  exteriorRows: [
    { part: "屋頂", items: [{ label: "屋頂", value: "瀝青防水（熱熔工法）" }, { label: "女兒牆", value: "與外牆裝修同規格" }, { label: "設備基礎", value: "砂漿裝修" }, { label: "鴿舍", value: "鍍鋅鋼板 t=0.35" }, { label: "屋頂檢修口", value: "鋁製" }] },
    { part: "屋頂陽台", items: [{ label: "", value: "瀝青防水（熱熔工法）●扶手：鋁製" }] },
    { part: "屋頂排水", items: [{ label: "", value: "不鏽鋼製" }] },
    { part: "落水管", items: [{ label: "", value: "PVC製 顏色：依外牆色" }] },
    { part: "外牆", items: [{ label: "", value: "塗裝：陶瓷矽樹脂塗裝 ●瓷磚：石紋瓷磚" }] },
    { part: "基礎立牆", items: [{ label: "", value: "砂漿裝修 顏色：依外牆色" }] },
    { part: "接縫", items: [{ label: "", value: "填縫材料：聚氨酯系" }] },
    { part: "開口部", items: [{ label: "出入口", value: "鋁製 隔熱窗框" }, { label: "玄關門", value: "防火門 隔熱規格" }, { label: "窗戶", value: "鋁製 隔熱窗框 Low-E複層玻璃" }, { label: "MB/PS", value: "鋁製" }] },
    { part: "外構", items: [{ label: "步道地面", value: "磁器質瓷磚" }, { label: "犬走道", value: "混凝土裝修" }, { label: "圍牆", value: "瓷磚貼面" }, { label: "共用龍頭", value: "不鏽鋼製" }] },
    { part: "其他", items: [{ label: "館銘板", value: "不鏽鋼製" }, { label: "管理員聯絡顯示板", value: "樹脂製" }, { label: "避難設備", value: "—" }, { label: "曬衣桿", value: "不鏽鋼製" }, { label: "滅火器", value: "各樓層設置" }] },
  ],
};
